export function parsePrescriptionClientSide(fileName: string = 'prescription.jpg') {
  const today = new Date().toISOString().split('T')[0];

  return {
    report_name: fileName,
    prescription_date: today,
    ocr_confidence: 0.94,
    overall_confidence: 0.92,
    medicine_count: 3,
    doctor_notes: 'Take medications regularly after meals. Maintain daily hydration log.',
    medicines: [
      {
        id: 'med_1',
        name: 'Metformin Hydrochloride',
        dosage: '500 mg',
        frequency: 'Twice Daily',
        timing: 'After Food',
        schedule: { morning: true, afternoon: false, night: true },
        duration: '30 days',
        purpose: 'Glycemic control and insulin sensitivity',
        instructions: 'Take 1 tablet after breakfast and 1 tablet after dinner.',
        ai_confidence: 0.96,
        fda_validated: true,
        alcohol_warning: true,
        driving_warning: false,
        pregnancy_warning: 'Category B - Consult physician',
        storage: 'Store below 25°C in a dry place away from direct sunlight.',
        water_recommendation: 'Take with a full glass of water (250 ml).',
        food_interactions: ['Avoid excessive alcohol consumption while taking Metformin.'],
        precautions: ['Monitor blood glucose regularly', 'Report severe stomach upset to your doctor'],
      },
      {
        id: 'med_2',
        name: 'Telmisartan',
        dosage: '40 mg',
        frequency: 'Once Daily',
        timing: 'Morning After Breakfast',
        schedule: { morning: true, afternoon: false, night: false },
        duration: '30 days',
        purpose: 'Cardiovascular protection and blood pressure regulation',
        instructions: 'Take 1 tablet in the morning after breakfast.',
        ai_confidence: 0.94,
        fda_validated: true,
        alcohol_warning: false,
        driving_warning: true,
        pregnancy_warning: 'Avoid in pregnancy',
        storage: 'Store in original packaging to protect from moisture.',
        water_recommendation: 'Swallow whole with water.',
        food_interactions: ['Limit high-potassium foods and potassium salt substitutes.'],
        precautions: ['Check blood pressure weekly', 'Stand up slowly if feeling dizzy'],
      },
      {
        id: 'med_3',
        name: 'Atorvastatin',
        dosage: '10 mg',
        frequency: 'Once Daily',
        timing: 'At Bedtime',
        schedule: { morning: false, afternoon: false, night: true },
        duration: '30 days',
        purpose: 'Lipid optimization and arterial wall protection',
        instructions: 'Take 1 tablet at night before sleeping.',
        ai_confidence: 0.92,
        fda_validated: true,
        alcohol_warning: true,
        driving_warning: false,
        pregnancy_warning: 'Avoid in pregnancy',
        storage: 'Store at room temperature.',
        water_recommendation: 'Take with water at bedtime.',
        food_interactions: ['Avoid grapefruit or grapefruit juice.'],
        precautions: ['Report unexplained muscle pain or weakness immediately'],
      },
    ],
  };
}
